version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.3
     steps:
       - checkout
       - restore_cache:
           key: rails-demo-{{ checksum "Gemfile.lock" }}
       - run: bundle install --path vendor/bundle
       - save_cache:
           key: rails-demo-{{ checksum "Gemfile.lock" }}
           paths:
             - vendor/bundle
       - run: bundle exec rspec spec
